PhoneCatalog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^phones/', include('phones.urls')),
    path('admin/', admin.site.urls),
]

phones/urls.py
from django.conf.urls import url
from . import views

app_name = 'phones'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^([0-9]+)/$', views.detail, name='detail'),
    url(r'^register/$', views.RegisterFormView.as_view()),
    url(r'^login/$', views.LoginFormView.as_view()),
    url(r'^logout/$', views.LogoutView.as_view()),
    url(r'^password-change/', views.PasswordChangeView.as_view()),
    # отправка сообщения
    url(r'^([0-9]+)/post/$', views.post, name='post'),
    # отправка списка сообщений
    url(r'^([0-9]+)/msg_list/$', views.msg_list, name='msg_list'),
    # отправка оценки
    url(r'^([0-9]+)/post_mark/$', views.post_mark, name='post_mark'),
    # средняя оценка
    url(r'^([0-9]+)/get_mark/$', views.get_mark, name='get_mark'),
    # добавление нового абонента
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^post_phone/$', views.post_phone, name='post_phone'),
    url(r'^subscribe/$', views.SubscribeView.as_view()),
    url(r'^unsubscribe/$', views.unsubscribe, name='unsubscribe'),
]

phones/models.py
from django.db import models
# встроенная модель пользователя нужна для авторов сообщений
from django.contrib.auth.models import User
# тип "временная зона" для получения текущего времени
from django.utils import timezone


class Subscriber(models.Model):
    Name = models.CharField(max_length=255)
    RegDate = models.DateTimeField('date published')
    Address = models.CharField(max_length=255)


class Phone(models.Model):
    IdSubscriber = models.ForeignKey(Subscriber, on_delete=models.CASCADE)
    PhoneNumber = models.CharField(max_length=30)


class Message(models.Model):
    chat = models.ForeignKey(Subscriber, verbose_name='Чат под абонентом', on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    message = models.TextField('Сообщение')
    pub_date = models.DateTimeField('Дата сообщения', default=timezone.now)


class Mark(models.Model):
    subscriber = models.ForeignKey(Subscriber, verbose_name='Абонент', on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    mark = models.IntegerField(verbose_name='Оценка')
    pub_date = models.DateTimeField('Дата оценки', default=timezone.now)

phones/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Subscriber, Phone, User
# Базовый класс для обработки страниц с формами.
from django.views.generic.edit import FormView
# Спасибо django за готовую форму регистрации.
from django.contrib.auth.forms import UserCreationForm
# Спасибо django за готовую форму аутентификации.
from django.contrib.auth.forms import AuthenticationForm
# Функция для установки сессионного ключа. По нему django будет определять, выполнил ли вход пользователь.
from django.contrib.auth import login
# Для Log out с перенаправлением на главную
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import logout
# Для смены пароля - форма
from django.contrib.auth.forms import PasswordChangeForm
# сообщения
from .models import Message
from datetime import datetime
# для ответа на асинхронный запрос в формате JSON
from django.http import JsonResponse
import json
# оценки
from .models import Mark
# вычисление среднего, например, средней оценки
from django.db.models import Avg
from django import forms
from django.utils.translation import gettext, gettext_lazy as _
from django.core.mail import send_mail


# главная страница
def index(request):
    message = None
    if "message" in request.GET:
        message = request.GET["message"]
    # создание HTML-страницы по шаблону index.html
    # с заданными параметрами latest_subscribers и message
    return render(
        request,
        "index.html",
        {
            "latest_subscribers":
                Subscriber.objects.order_by('Name')[:5],
            "message": message
        }
    )


# страница список телефонов для абонента
def detail(request, subscriber_id):
    error_message = None
    if "error_message" in request.GET:
        error_message = request.GET["error_message"]

    return render(
        request,
        "phones.html",
        {
            "subscriber": get_object_or_404(Subscriber, pk=subscriber_id),
            "error_message": error_message,
            "latest_messages": Message.objects.filter(chat_id=subscriber_id).order_by('-pub_date')[:5],
            # кол-во оценок, выставленных пользователем
            "already_rated_by_user": Mark.objects.filter(author_id=request.user.id).count(),
            # оценка текущего пользователя
            "user_rating":
                Mark.objects
                    .filter(author_id=request.user.id)
                    .filter(subscriber_id=subscriber_id)
                    .aggregate(Avg('mark'))["mark__avg"],
            # средняя по всем пользователям оценка
            "avg_mark": Mark.objects.filter(subscriber_id=subscriber_id).aggregate(Avg('mark'))["mark__avg"]
        }

    )


# базовый URL приложения, главной страницы - часто нужен при указании путей переадресации
app_url = "/phones/"


# наше представление для регистрации
class RegisterFormView(FormView):
    # будем строить на основе встроенной в django формы регистрации
    form_class = UserCreationForm
    # Ссылка, на которую будет перенаправляться пользователь в случае успешной регистрации.
    # В данном случае указана ссылка на страницу входа для зарегистрированных пользователей.
    success_url = app_url + "login/"
    # Шаблон, который будет использоваться при отображении представления.
    template_name = "reg/register.html"

    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()
        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)


# наше представление для входа
class LoginFormView(FormView):
    # будем строить на основе встроенной в django формы входа
    form_class = AuthenticationForm
    # Аналогично регистрации, только используем шаблон аутентификации.
    template_name = "reg/login.html"
    # В случае успеха перенаправим на главную.
    success_url = app_url

    def form_valid(self, form):
        # Получаем объект пользователя на основе введённых в форму данных.
        self.user = form.get_user()
        # Выполняем аутентификацию пользователя.
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


# для выхода - миниатюрное представление без шаблона - после выхода перенаправим на главную
class LogoutView(View):
    def get(self, request):
        # Выполняем выход для пользователя, запросившего данное представление.
        logout(request)
        # После чего перенаправляем пользователя на главную страницу.
        return HttpResponseRedirect(app_url)


# наше представление для смены пароля
class PasswordChangeView(FormView):
    # будем строить на основе встроенной в django формы смены пароля
    form_class = PasswordChangeForm
    template_name = 'reg/password_change_form.html'
    # после смены пароля нужно снова входить
    success_url = app_url + 'login/'

    def get_form_kwargs(self):
        kwargs = super(PasswordChangeView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(PasswordChangeView, self).form_valid(form)


# функция для добавления сообщений для определенного абонента
def post(request, subscriber_id):
    msg = Message()
    msg.author = request.user
    msg.chat = get_object_or_404(Subscriber, pk=subscriber_id)
    msg.message = request.POST['message']
    msg.pub_date = datetime.now()
    msg.save()
    return HttpResponseRedirect(app_url + str(subscriber_id))


# функция, возвращающую список сообщений к абоненту в формате JSON
def msg_list(request, subscriber_id):
    # выбираем список сообщений
    res = list(
        Message.objects
            # фильтруем по id абонента
            .filter(chat_id=subscriber_id)
            # отбираем 5 самых свежих
            .order_by('-pub_date')[:5]
            # выбираем необходимые поля
            .values('author__username', 'pub_date', 'message')
    )
    # конвертируем даты в строки - сами они не умеют
    for r in res:
        r['pub_date'] = r['pub_date'].strftime('%d.%m.%Y %H:%M:%S')

    return JsonResponse(json.dumps(res), safe=False)


# функция для добавление оценки абоненту
def post_mark(request, subscriber_id):
    msg = Mark()
    msg.author = request.user
    msg.subscriber = get_object_or_404(Subscriber, pk=subscriber_id)
    msg.mark = request.POST['mark']
    msg.pub_date = datetime.now()
    msg.save()
    return HttpResponseRedirect(app_url + str(subscriber_id))


# функция, возвращающуя среднюю оценку загадки в формате JSON
def get_mark(request, subscriber_id):
    res = Mark.objects.filter(subscriber_id=subscriber_id).aggregate(Avg('mark'))

    return JsonResponse(json.dumps(res), safe=False)


# отображениу администраторской панели добавления телефонов
def admin(request):
    message = None
    if "message" in request.GET:
        message = request.GET["message"]
    # создание HTML-страницы по шаблону admin.html
    # с заданными параметрами latest_subscribers и message
    return render(
        request,
        "admin.html",
        {
            "latest_subscribers": Subscriber.objects.order_by('Name')[:5],
            "message": message,
        }
    )


def post_phone(request):
    # защита от добавления абонентов неадминистраторами
    author = request.user
    if not (author.is_authenticated and author.is_staff):
        return HttpResponseRedirect(app_url + "admin")
    # добавление загадки
    subscriber = Subscriber()
    subscriber.Name = request.POST['fio']
    subscriber.Address = request.POST['address']
    subscriber.RegDate = datetime.now()
    subscriber.save()
    # добавление телефонов
    i = 1  # нумерация вариантов на форме начинается с 1
    # количество вариантов неизвестно, поэтому ожидаем возникновение исключения, когда варианты кончатся
    try:
        while request.POST['phone' + str(i)]:
            phone = Phone()
            phone.IdSubscriber = subscriber
            phone.PhoneNumber = request.POST['phone' + str(i)]
            phone.save()
            i += 1
    # это ожидаемое исключение, при котором ничего делать не надо
    except:
        pass

    # цикл по всем пользователям
    for i in User.objects.all():
        # проверка, что текущий пользователь подписан - указал e-mail
        if i.email != '':
            send_mail(
                # тема письма
                'Новый абонент',
                # текст письма
                'Новый абонент был добавлен на сайте:\n' +
                'http://localhost:8000/phones/' + str(subscriber.id) + '.',
                # отправитель
                'tarasovayuliya1.19@gmail.com',
                # список получателей из одного получателя
                [i.email],
                # отключаем замалчивание ошибок,
                # чтобы из видеть и исправлять
                False
            )

    return HttpResponseRedirect(app_url + str(subscriber.id))


# класс, описывающий логику формы: список заполняемых полей и их сохранение
class SubscribeForm(forms.Form):
    # поле для ввода e-mail
    email = forms.EmailField(label=_("E-mail"), required=True, )

    # конструктор для запоминания пользователя, которому задается e-mail
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    # сохранение e-mail
    def save(self, commit=True):
        self.user.email = self.cleaned_data["email"]
        if commit:
            self.user.save()
        return self.user


# класс, описывающий взаимодействие логики со страницами веб-приложения
class SubscribeView(FormView):
    # используем класс с логикой
    form_class = SubscribeForm
    # используем собственный шаблон
    template_name = 'subscribe.html'
    # после подписки возвращаем на главную станицу
    success_url = app_url

phones/templates/admin.html
{% extends 'base.html' %}
{% block main %}
    {% if user.is_staff %}
        {% if message %}
            <p class="alert alert-success"><strong>{{ message }}</strong></p>
        {% endif %}
        <div class="card mb-3">
            <div class="card-body">
                <form action="../post_phone/" method="post">
                    {% csrf_token %}
                    <h5>Добавить нового абонента:</h5>
                    <div class="mb-3">
                        <input class="form-control" placeholder="Введите ФИО абонента" name="fio" required/>
                    </div>
                    <div class="mb-3">
                        <input class="form-control" placeholder="Введите адрес абонента" name="address" required/>
                    </div>
                    <div class="card mb-3">
                        <div class="card-body" id="phones_new">
                            <div class="mb-3">
                                <input class="form-control" placeholder="Введите номер телефона" name="phone1"
                                       required/>
                            </div>
                            <script>
                                var option_counter = 1;
                            </script>
                        </div>
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-success" onclick="addPhone('phones_new', 0)" type="button">
                            + Добавить телефон
                        </button>
                        <button class="btn btn-success"> Сохранить</button>
                    </div>
                    <input type="hidden" name="phone_id" value="0"/>
                </form>
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-body">
                <h4 class="card-title">Список абонентов</h4>
                {% if latest_subscribers %}
                    {% for Subscriber in latest_subscribers %}
                        <li>
                            <a href="/phones/{{ Subscriber.id }}/">{{ Subscriber.Name }}</a>, {{ Subscriber.Address }}
                        </li>
                    {% endfor %}
                {% else %}
                    <p>Справочник пустой.</p>
                {% endif %}
            </div>
        </div>

        <script>
            //добавление блока для нового ответа
            function addPhone(target, pos_in_array) {
                var option = document.createElement("div");
                option_counter += 1;
                option.className = "input-group mb-3";
                option.innerHTML =
                    '<input class="form-control"' +
                    '       placeholder="Телефон ' +
                    option_counter + '"' +
                    '       name="phone' + option_counter + '"/>' +
                    '<div class="input-group-append">' +
                    '     <button class="btn btn-danger"' +
                    '             type="button"' +
                    '             onclick="removeParent(' +
                    '               this.parentNode)">' +
                    '          Delete' +
                    '     </button>' +
                    '</div>';
                document.getElementById(target).appendChild(option);
            }

            //удаление блока ответа с поправкой номеров других ответов
            function removeParent(child) {
                var optionList = child.parentNode.parentNode;
                var currentPhone = child.parentNode;
                optionList.removeChild(currentPhone);
                for (var i = 3; i < optionList.children.length; i += 1) {
                    var opt = optionList.children[i].children[0];
                    opt.name = "phone" + (i);
                    opt.placeholder = "Телефон " + (i);
                }
                option_counter -= 1;
            }
        </script>
    {% else %}
        <h4>Access denied.</h4>
    {% endif %}
{% endblock %}

phones/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <title>Телефонный справочник</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2">Телефонный справочник</h1>
            {% if user.is_authenticated %}
                <p class="text-right">
                    Привет, {{ user.username }}!
                    <a href="/phones/logout">Выйти</a> |
                    <a href="/phones/password-change"> Сменить пароль </a>
                    {% if user.is_staff %}
                        | <a href="/phones/admin">Добавить абонента</a>
                    {% endif %}
                    {% if user.email == '' %}
                        | <a href="/phones/subscribe">Подписаться</a>
                    {% else %}
                        | <a href="/phones/unsubscribe">Отписаться</a>
                    {% endif %}
                </p>
            {% else %}
                <p class="text-right">
                    <a href="/phones/login">Войти</a> |
                    <a href="/phones/register">Зарегистрироваться</a>
                </p>
            {% endif %}
            <hr class="mt-0 mb-4">
            <div class="card">
                <div class="card-body">
                    {% block main %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

phones/templates/index.html
{% extends 'base.html' %}
{% block main %}
    <h4 class="card-title">Список абонентов</h4>

    {% if message %}
        <p class="alert alert-success">
            <strong>{{ message }}</strong>
        </p>
    {% endif %}

    {% if latest_subscribers %}
        {% for Subscriber in latest_subscribers %}
            <li>
                <a href="/phones/{{ Subscriber.id }}/">{{ Subscriber.Name }}</a>, {{ Subscriber.Address }}
            </li>
        {% endfor %}
    {% else %}
        <p>Справочник пустой.</p>
    {% endif %}
{% endblock %}

phones/templates/phones.html
{% extends 'base.html' %}

{% block main %}
    <h4 class="card-title">{{ subscriber.Name }}</h4>
    <p>{{ subscriber.Address }}</p>

    {% if error_message %}
        <p class="alert alert-danger">
            <strong>{{ error_message }}</strong>
        </p>
    {% endif %}

    {% for phone in subscriber.phone_set.all %}
        <p> {{ phone.PhoneNumber }} </p>
    {% endfor %}

    <p><a href="/phones/">Вернуться к списку абонентов</a></p>

    <hr>
    <h4>Рейтинг</h4>
    <p>Средняя оценка: <span id="avg_mark_span">{{ avg_mark }}</span></p>
    {% if user.is_authenticated %}
        {% if already_rated_by_user == 0 %}
            <form action="post_mark/" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm text-center">
                        <input name="mark" type="radio" value="1"/> 1
                    </div>
                    <div class="col-sm text-center">
                        <input name="mark" type="radio" value="2"/> 2
                    </div>
                    <div class="col-sm text-center">
                        <input name="mark" type="radio" value="3"/> 3
                    </div>
                    <div class="col-sm text-center">
                        <input name="mark" type="radio" value="4"/> 4
                    </div>
                    <div class="col-sm text-center">
                        <input name="mark" type="radio" value="5"/> 5
                    </div>
                    <div class="col-sm text-center">
                        <input class="btn btn-success" type="submit" value="Оценить"/>
                    </div>
                </div>
            </form>
        {% else %}
            Ваша оценка: {{ user_rating }}
        {% endif %}

    {% endif %}

    <hr>
    <h4>Чат</h4>
    {% if user.is_authenticated %}
        <form action="post/" method="post">
            {% csrf_token %}
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Your message" name="message"/>
                <div class="input-group-append">
                    <input class="btn btn-success" type="submit" value="Send"/>
                </div>
            </div>
        </form>
    {% endif %}

    <div id="history">
        {% for message in latest_messages %}
            <div class="card">
                <div class="card-body">
                    <strong>
                        {{ message.author.username }}
                    </strong>
                    <br/>
                    <em>
                        {{ message.pub_date|date:'Y-m-d H:i:s' }}
                    </em>
                    <br/>
                    {{ message.message }}
                </div>
            </div>
            <br/>
        {% endfor %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script>
        function send_msg_update_request() {
            $.get("msg_list/", {}, parse_msg_update_response);
            $.get("get_mark/",{},parse_mark_update_response);
        }

        function parse_msg_update_response(data, success) {
            //alert(data);
            res = JSON.parse(data);
            res_str = "";
            for (i = 0; i < res.length; i++) {
                // HTML-код вставляемых блоков с сообщениями скопирован выше - тот, что выводится при загрузке страницы
                res_str += '<div class="card">\n' +
                    '        <div class="card-body">\n' +
                    '            <strong>\n' +
                    '                ' + res[i].author__username + '\n' +
                    '            </strong>\n' +
                    '            <br/>\n' +
                    '            <em>\n' +
                    '                ' + res[i].pub_date + '\n' +
                    '            </em>\n' +
                    '            <br/>\n' +
                    '            ' + res[i].message + '\n' +
                    '        </div>\n' +
                    '        </div>\n' +
                    '        <br/>'
            }
            $("#history").html(res_str);
        }

        function parse_mark_update_response(data, success){
            res = JSON.parse(data);
            $("#avg_mark_span").html(res["mark__avg"].toFixed(1));
        }

        setInterval(send_msg_update_request, 5000);
    </script>

{% endblock %}

phones/templates/subscribe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success btn-block"> Подписаться</button>
        <a href=".." class="btn btn-danger btn-block"> Вернуться на главную </a>
    </form>
{% endblock %}